apiVersion: v1beta3
kind: Service
metadata:
    labels:
        name: cassandra
    name: cassandra
spec:
    ports:
        - name: native
          port: 9042
        - name: thrift
          port: 9160
    publicIPs: [ 10.1.102.103 ]
    selector:
        name: cassandra
