apiVersion: v1beta3
kind: Pod
metadata:
    labels:
        name: cassandra
    name: cassandra
spec:
    containers:
      - name: cassandra
        image: mikeln/cassandra_kub_mln:v11
        ports:
          - name: cql
            containerPort: 9042
          - name: thrift
            containerPort: 9160
          - name: jmx
            containerPort: 7199
          - name: huh
            containerPort: 7000
          - name: huh-ssl
            containerPort: 7001
          - name: agent
            containerPort: 61620
          - name: agent-ssl
            containerPort: 61621
          - name: dse
            containerPort: 50031
        volumeMounts:
          - name: data
            mountPath: /cassandra_data
        env:
#          - name: MAX_HEAP_SIZE
#            value: 512M
#          - name: HEAP_NEWSIZE
#            value: 100M
#          - name: KUBERNETES_API_PROTOCOL
#            value: http
    volumes:
      - name: data
        emptyDir: {}
    restartPolicy: Never
