apiVersion: v1
kind: Service
metadata:
    labels:
        name: cassandra
    name: cassandra
spec:
    ports:
        - name: native
          port: 9042
          nodeport: 30042
        - name: thrift
          port: 9160
          nodeport: 30160
    selector:
        name: cassandra
    type: NodePort
