apiVersion: v1
kind: ReplicationController
metadata:
    labels:
        name: cassandra
    name: cassandra
spec:
  replicas: 2
  selector:
    name: cassandra
  template:
    metadata:
        labels:
            name: cassandra
    spec:
        containers:
          - name: cassandra
            image: quay.io/mikeln/cassandra_kub:v21slim
            resources:
                limits:
                    cpu: 1
            ports:
              - name: cql
                containerPort: 9042
              - name: thrift
                containerPort: 9160
              - name: jmx
                containerPort: 7199
              - name: huh
                containerPort: 7000
              - name: huh-ssl
                containerPort: 7001
              - name: agent
                containerPort: 61620
              - name: agent-ssl
                containerPort: 61621
              - name: dse
                containerPort: 50031
            volumeMounts:
              - name: data
                mountPath: /cassandra_data
            env:
              - name: MAX_HEAP_SIZE
                value: 512M
              - name: HEAP_NEWSIZE
                value: 100M
        volumes:
          - name: data
            emptyDir: {}
