apiVersion: v1beta3
kind: Service
metadata:
    labels: 
        name: opscenter
    name: opscenter
spec:
    ports:
        - name: webui
          port: 8888
          targetPort: 8888
    publicIPs: [ 172.16.1.103, 172.16.1.104 ]
    selector:
        name: opscenter

