id: opscenter
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest:
    version: v1beta1
    id: opscenter
    containers:
      - name: opscenter
        image: mikeln/opscenter-kub-mln:v1
        cpu: 1000
        ports:
          - name: cql
            containerPort: 9042
          - name: thrift
            containerPort: 9160
          - name: jmx
            containerPort: 7199
          - name: huh
            containerPort: 7000
          - name: huh-ssl
            containerPort: 7001
          - name: agent
            containerPort: 61620
          - name: agent-ssl
            containerPort: 61621
          - name: dse
            containerPort: 50031
        env:
          - key: MAX_HEAP_SIZE
            value: 512M
          - key: HEAP_NEWSIZE
            value: 100M
          - key: KUBERNETES_API_PROTOCOL
            value: http
labels:
  name: opscenter

    
