apiVersion: v1
kind: Service
metadata:
    labels: 
        name: opscenter
    name: opscenter
spec:
    ports:
        - name: opsui
          port: 30888
          targetport: 30888
          nodeport: 30888
    selector:
        name: opscenter
    type: NodePort

