apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "statefulname" . }}-op
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  replicas: {{ default 1 .Values.opscenter.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "statefulname" . }}-op
    spec:
      containers:
      - name: {{ template "statefulname" . }}-op
        image: "{{ .Values.opscenter.image.repository }}:{{ .Values.opscenter.image.tag }}"
        imagePullPolicy: {{ .Values.opscenter.image.pullPolicy }}
        env:
        - name: SEED_NODE_SERVICE
          value: '{{ template "statefulname" . }}-0.{{ template "statefulname" . }}.{{ .Release.Namespace }}.svc.cluster.local'
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports: 
        {{ range .Values.opscenter.ports }}- containerPort: {{ .port }}
        {{ end }}
        command: 
        {{ range .Values.opscenter.command}}- {{ . }}
        {{ end }}
        resources:
{{ toYaml .Values.opscenter.resources | indent 10}}
