{{- if (.Values.cassandra.secret.adminpw)  (.Values.cassandra.secret.opspw)  (.Values.cassandra.secret.zonarpw) -}}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ template "name" . }}
  labels:
    name: {{ template "name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ template "name" . }}
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
type: Opaque
data:
  AdminPassword: {{ .Values.cassandra.secret.adminpw | b64enc | quote }}
  OpsCenterPassword: {{ .Values.cassandra.secret.opspw | b64enc | quote }}
  ZonarPassword: {{ .Values.cassandra.secret.zonarpw | b64enc | quote }}
{{- else -}}
{{ if .Passwords.missing }}
{{ end }}
{{- end -}}
