apiVersion: v1
kind: Service
metadata:
  name: {{ template "statefulname" . }}-op
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.serviceOpscenter.type }}
  ports: 
    {{ range .Values.serviceOpscenter.ports }}- port: {{ .port }}
      targetPort: {{.targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{end}}
  selector:
    app: {{ template "statefulname" . }}-op
